// Generated by Wrangler on Sun May 12 2024 13:35:06 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
  MY_DO_NAMESPACE: DurableObjectNamespace;
  MY_QUEUE: Queue;
}
